
import static java.nio.file.Files.list;
import static java.rmi.Naming.list;
import java.util.ArrayList;
import static java.util.Collections.list;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class InsertarAlumno extends javax.swing.JFrame {
public ArrayList<Alumnos> listaAlumnos;
     
    public InsertarAlumno() {
        initComponents();
        listaAlumnos=new ArrayList<>(4);
        this.setLocationRelativeTo(null);
        etError.setVisible(false);
    }
    
        public void listar(){
        DefaultListModel modelo=new DefaultListModel();
        for (int i=0;i<listaAlumnos.size();i++){
            if (i<5)
            modelo.addElement(listaAlumnos.get(i).getNombre() +", "+ listaAlumnos.get(i).getApellidos()+", "+listaAlumnos.get(i).getEmail()+", "+ listaAlumnos.get(i).getEdad()+", "+listaAlumnos.get(i).getTelefono());
            else etError.setVisible(true);
        }
       
        ListaAlumnos.setModel(modelo); 
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmpApe = new javax.swing.JTextField();
        cmpNom = new javax.swing.JTextField();
        cmpEm = new javax.swing.JTextField();
        cmpEd = new javax.swing.JTextField();
        cmpTel = new javax.swing.JTextField();
        butAñadir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaAlumnos = new javax.swing.JList<>();
        etError = new javax.swing.JLabel();
        lblLetra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmpApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpApeActionPerformed(evt);
            }
        });

        cmpNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpNomActionPerformed(evt);
            }
        });

        cmpEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpEmActionPerformed(evt);
            }
        });

        cmpEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpEdActionPerformed(evt);
            }
        });

        cmpTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpTelActionPerformed(evt);
            }
        });

        butAñadir.setText("Añadir");
        butAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAñadirActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Email");

        jLabel4.setText("Edad");

        jLabel5.setText("Telefono");

        jScrollPane1.setViewportView(ListaAlumnos);

        etError.setForeground(java.awt.Color.red);
        etError.setText("¡HAS EXCEDIDO EL  LIMITE DE ALUMNOS!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmpTel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmpEd, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmpNom, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmpApe, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmpEm, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(butAñadir)
                .addGap(18, 18, 18)
                .addComponent(etError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLetra)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmpNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cmpApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmpEm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cmpEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmpTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(butAñadir)
                            .addComponent(etError)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblLetra)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmpApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpApeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpApeActionPerformed

    private void cmpNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpNomActionPerformed

    private void cmpEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpEmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpEmActionPerformed

    private void cmpEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpEdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpEdActionPerformed

    private void cmpTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmpTelActionPerformed

    private void butAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAñadirActionPerformed
         Alumnos alumno=new Alumnos();
        String nombre, apellidos,email, edaad;
        int edad, telefono;
        int menor=200;
        try {
       
            alumno.setNombre(cmpNom.getText());
            alumno.setApellidos(cmpApe.getText());
            alumno.setEmail(cmpEm.getText());
            
            edad=Integer.parseInt(cmpEd.getText());
            alumno.setEdad(edad);
            
            telefono=Integer.parseInt(cmpTel.getText());
            alumno.setTelefono(telefono);
           
            
            listaAlumnos.add(alumno);
            listar();
            JOptionPane.showMessageDialog(null,"Se agrego correctamente","Agregar",JOptionPane.INFORMATION_MESSAGE); 
            
            
            
            for (int i=0; i<listaAlumnos.size();i++){
            if (listaAlumnos.get(i).getEdad()<menor){
                menor=listaAlumnos.get(i).getEdad();
                this.lblLetra.setText(listaAlumnos.get(i).getNombre()+" "+listaAlumnos.get(i).getApellidos());
            }}

            
            
        }
        
        catch (ArrayIndexOutOfBoundsException e) {   
         
        }
    }//GEN-LAST:event_butAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaAlumnos;
    private javax.swing.JButton butAñadir;
    private javax.swing.JTextField cmpApe;
    private javax.swing.JTextField cmpEd;
    private javax.swing.JTextField cmpEm;
    private javax.swing.JTextField cmpNom;
    private javax.swing.JTextField cmpTel;
    private javax.swing.JLabel etError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLetra;
    // End of variables declaration//GEN-END:variables
}
